### ISSUE TITLE
The build is failling during test case

### ISSUE THREAD

**Issue by pnaik1** [nodeshift-starters/nodejs-configmap#227]
The failure is due to the ESLint
npm run test

> nodejs-configmap@4.0.0 pretest /home/pnaik/Music/place/nodejs-configmap
> eslint --ignore-path .gitignore .

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/home/pnaik/Music/place/nodejs-configmap/node_modules/eslint-config-semistandard/index.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nodejs-configmap@4.0.0 pretest: `eslint --ignore-path .gitignore .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nodejs-configmap@4.0.0 pretest script.

**Comment by helio-frota** [comment]
closing , looks similar to https://github.com/nodeshift-starters/nodejs-rest-http/issues/219
