### ISSUE TITLE
'Unable to read the configuration' when deployed to the OpenShift Sandbox

### ISSUE THREAD

**Issue by BethGriggs** [nodeshift-starters/nodejs-configmap#230]
I followed the instructions in the README, but the application outputs 'Unable to read the configuration' when deployed to the sandbox.

**Comment by helio-frota** [comment]
@BethGriggs thanks for reporting this, that is probably something we missed because since the beginning we are doing local deployments

**Comment by helio-frota** [comment]
@BethGriggs This is happening in OpenShift local as well
Interesting because the file is on the right location.

![2022-09-06_09-59](https://user-images.githubusercontent.com/6443576/188641544-61e901a5-1bcc-469f-b9aa-7eb8b0dcc018.png)
