### ISSUE TITLE
Error when clicking "invoke" button

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/nodejs-configmap#92]
![2019-07-01_17-44](https://user-images.githubusercontent.com/6443576/60465661-08192000-9c28-11e9-8c38-5f7425e9b09c.png)

**Comment by lholmquist** [comment]
Have you also created the configmap on Openshift and set the correct permissions,

have a look at https://appdev.openshift.io/docs/nodejs-runtime.html#example-configmap-nodejs

**Comment by helio-frota** [comment]
@lholmquist Thanks I'll take a look

**Comment by helio-frota** [comment]
It is working.
Added a missing config command to the docs: https://github.com/nodeshift-starters/nodejs-configmap/commit/707182fd97d3d561334a3ee9af54c2cf1e43469c

![2019-07-23_15-13](https://user-images.githubusercontent.com/6443576/61736768-312b5d00-ad5d-11e9-81be-d9c0ce4a6acc.png)
